services:
  mongodb:
    image: mongo:7
    container_name: pok-team-builder-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DB: pok_team_builder
    ports:
      - "27017:27017"
    volumes:
      - pok_team_builder_data:/data/db

volumes:
  pok_team_builder_data:
